import 'dart:math';

import 'constants.dart';
import 'generator.dart';

/// Creates a custom NanoID generator function with a fixed alphabet.
///
/// This is useful when you need to generate many IDs with the same custom alphabet,
/// as it validates the alphabet once and returns a closure that can be called
/// repeatedly.
///
/// The returned function generates IDs using the specified [alphabet] and
/// cryptographically secure random values. Each call creates a new unique ID.
///
/// Parameters:
/// - [alphabet]: The alphabet to use for ID generation. Must not be empty
///   and cannot exceed 256 characters.
/// - [defaultSize]: Optional default size for IDs generated by the returned function.
///   Defaults to 21 characters. The returned function can override this with its
///   own size parameter.
///
/// Returns a function that takes an optional [size] parameter and returns
/// a randomly generated ID string.
///
/// Throws:
/// - [ArgumentError] if [alphabet] is empty or exceeds 256 characters
/// - [ArgumentError] if [defaultSize] is less than or equal to 0
///
/// Examples:
/// ```dart
/// // Create a generator for numeric IDs
/// final numericId = customAlphabet('0123456789');
/// print(numericId()); // => "394759238475629387465" (21 digits)
/// print(numericId(size: 6)); // => "847562" (6 digits)
///
/// // Create a generator for hex IDs with custom default size
/// final hexId = customAlphabet('0123456789ABCDEF', defaultSize: 8);
/// print(hexId()); // => "A3F5B2E1" (8 chars)
/// print(hexId(size: 16)); // => "A3F5B2E19C4D8F7A" (16 chars)
///
/// // Create a generator for lowercase alphanumeric
/// final alphanumeric = customAlphabet(
///   'abcdefghijklmnopqrstuvwxyz0123456789',
/// );
/// print(alphanumeric(size: 10)); // => "k3b8d9j2a1"
/// ```
String Function({int size}) customAlphabet(
  String alphabet, {
  int defaultSize = defaultSize,
}) {
  // Validate inputs once at creation time
  validateAlphabet(alphabet);
  validateSize(defaultSize);

  // Create and return the generator closure
  return ({int? size}) {
    final effectiveSize = size ?? defaultSize;

    // Validate the size parameter
    validateSize(effectiveSize);

    // Generate ID using cryptographically secure random
    final random = Random.secure();
    return generate(effectiveSize, alphabet, random);
  };
}
